/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasidatabase2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 100 Mbps
 */
public class MainFormAplikasiDatabase2 extends javax.swing.JFrame {
    
    ResultSet result;
    Statement statemen;
    Connection koneksi;
    Boolean isUbah = false, isTambah = false;

    /**
     * Creates new form MainFormAplikasiDatabase2
     */
    public MainFormAplikasiDatabase2() {
        initComponents();
        doConnect();
    }
    
    public void doConnect() {
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            String Host     = "jdbc:mysql://localhost:3306/latihan_db";
            String Username = "root";
            String Password = "";
            koneksi = DriverManager.getConnection(Host,Username,Password);
            
            statemen = koneksi.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, 
                    ResultSet.CONCUR_UPDATABLE);
            String sql = "SELECT * FROM biodata_mhs ORDER BY nim ASC";
            result = statemen.executeQuery(sql);
            
            //Pindahkan Kursor pada Record Pertama
            result.first();
            TampilData();
            
        } catch (IllegalAccessException | ClassNotFoundException | InstantiationException | SQLException ex) {
            Logger.getLogger(MainFormAplikasiDatabase2.class.getName()).log(Level.SEVERE,null,ex);
        }
    }
    
    private void TampilData() throws SQLException {
        txtNim.setText(result.getString("nim"));
        txtNama.setText(result.getString("nama"));
        
        String kelamin = result.getString("jenis_kelamin");
        switch (kelamin) {
            case"L":
                rbL.setSelected(true);
                break;
            case"P":
                rbP.setSelected(true);
                break;
        }
        
        txtTanggalLahir.setText(result.getString("tanggal_lahir"));
        txtAlamat.setText(result.getString("alamat"));
        txtFakultas.setText(result.getString("fakultas"));
        txtJurusan.setText(result.getString("jurusan"));
        txtAngkatan.setText(result.getString("angkatan"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupJK = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblNim = new javax.swing.JLabel();
        txtNim = new javax.swing.JTextField();
        lblNama = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        lblJenisKelamin = new javax.swing.JLabel();
        rbL = new javax.swing.JRadioButton();
        rbP = new javax.swing.JRadioButton();
        lblTanggalLahir = new javax.swing.JLabel();
        txtTanggalLahir = new javax.swing.JTextField();
        lblAlamat = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        lblFakultas = new javax.swing.JLabel();
        txtFakultas = new javax.swing.JTextField();
        lblJurusan = new javax.swing.JLabel();
        txtJurusan = new javax.swing.JTextField();
        lblAngkatan = new javax.swing.JLabel();
        txtAngkatan = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKiri = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnKanan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("BIODATA MAHASISWA");

        lblNim.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNim.setText("NIM");

        lblNama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNama.setText("Nama");

        lblJenisKelamin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblJenisKelamin.setText("Jenis Kelamin");

        btnGroupJK.add(rbL);
        rbL.setText("Laki-Laki");

        btnGroupJK.add(rbP);
        rbP.setText("Perempuan");

        lblTanggalLahir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTanggalLahir.setText("Tanggal Lahir");

        lblAlamat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAlamat.setText("Alamat");

        lblFakultas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblFakultas.setText("Fakultas");

        lblJurusan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblJurusan.setText("Jurusan");

        lblAngkatan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAngkatan.setText("Angkatan");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnKiri.setText("<<");
        btnKiri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKiriActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnKanan.setText(">>");
        btnKanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKananActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNim)
                            .addComponent(lblNama)
                            .addComponent(lblJenisKelamin)
                            .addComponent(lblTanggalLahir)
                            .addComponent(lblAlamat)
                            .addComponent(lblFakultas)
                            .addComponent(lblJurusan)
                            .addComponent(lblAngkatan))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbP))
                            .addComponent(txtTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFakultas, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAngkatan, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btnTambah)
                        .addGap(18, 18, 18)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btnKiri)
                        .addGap(47, 47, 47)
                        .addComponent(btnKanan)))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(166, 166, 166))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNim)
                    .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNama)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJenisKelamin)
                    .addComponent(rbL)
                    .addComponent(rbP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTanggalLahir)
                    .addComponent(txtTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlamat)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFakultas)
                    .addComponent(txtFakultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJurusan)
                    .addComponent(txtJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAngkatan)
                    .addComponent(txtAngkatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnSimpan)
                    .addComponent(btnHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKiri)
                    .addComponent(btnKanan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClose)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnKiriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKiriActionPerformed
        try {
            if (!result.isFirst()) {
                result.previous();
                TampilData();
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainFormAplikasiDatabase2.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_btnKiriActionPerformed

    private void btnKananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKananActionPerformed
        try {
            if (!result.isLast()) {
                result.next();
                TampilData();
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainFormAplikasiDatabase2.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_btnKananActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try {
            result.updateString("nim",txtNim.getText());
            result.updateString("nama",txtNama.getText());
            
            String kelamin = null;
            if (rbL.isSelected())
                kelamin = "L";
            else if (rbP.isSelected())
                kelamin = "P";
            result.updateString("jenis_kelamin",kelamin);
            
            SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
            try {
                java.util.Date date = formater.parse(txtTanggalLahir.getText());
                java.sql.Date sqlDate = new java.sql.Date (date.getTime());
                result.updateDate("tanggal_lahir",(java.sql.Date) sqlDate);
            } catch (ParseException e) {
            }
            
            result.updateString("alamat",txtAlamat.getText());
            result.updateString("fakultas",txtFakultas.getText());
            result.updateString("jurusan",txtJurusan.getText());
            result.updateString("angkatan",txtAngkatan.getText());
            
            int opsi = JOptionPane.showConfirmDialog(null, "Ubah Data?", "PERINGATAN", JOptionPane.YES_NO_OPTION);
            switch(opsi){
                case JOptionPane.YES_OPTION:
                    result.updateRow();
                    JOptionPane.showMessageDialog(null, "Data Berhasil diubah.");
                    result.next();
                    result.first();
                    TampilData();
                    break;
                case JOptionPane.NO_OPTION:
                    TampilData();
                    break;
            }
        } catch (final SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        try {
            result.moveToInsertRow();
            
            result.updateString("nim", txtNim.getText());
            result.updateString("nama", txtNama.getText());
            
            String kelamin = null;
            if (rbL.isSelected())
                kelamin = "L";
            else if (rbP.isSelected())
                kelamin = "P";
            result.updateString("jenis_kelamin",kelamin);
            
            SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
            try {
                java.util.Date date = formater.parse(txtTanggalLahir.getText());
                java.sql.Date sqlDate = new java.sql.Date (date.getTime());
                result.updateDate("tanggal_lahir",(java.sql.Date) sqlDate);
            } catch (ParseException e) {
            }
            
            result.updateString("alamat",txtAlamat.getText());
            result.updateString("fakultas",txtFakultas.getText());
            result.updateString("jurusan",txtJurusan.getText());
            result.updateString("angkatan",txtAngkatan.getText());
            
            int opsi = JOptionPane.showConfirmDialog(null, "Tambah Data?", "PERINGATAN", JOptionPane.YES_NO_OPTION);
            switch(opsi){
                case JOptionPane.YES_OPTION:
                    result.insertRow();
                    JOptionPane.showMessageDialog(null, "Data Berhasil ditambah.");
                    result.next();
                    result.first();
                    TampilData();
                    break;
                case JOptionPane.NO_OPTION:
                    TampilData();
                    break;
            }
        } catch (final SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try {
            result.updateString("nim", txtNim.getText());
            result.updateString("nama", txtNama.getText());
            
            String kelamin = null;
            result.updateString("jenis_kelamin",kelamin);
            
            result.updateString("tanggal_lahir",txtTanggalLahir.getText());
            result.updateString("alamat",txtAlamat.getText());
            result.updateString("fakultas",txtFakultas.getText());
            result.updateString("jurusan",txtJurusan.getText());
            result.updateString("angkatan",txtAngkatan.getText());
            
            int opsi = JOptionPane.showConfirmDialog(null, "Hapus Data?", "PERINGATAN", JOptionPane.YES_NO_OPTION);
            switch(opsi){
                case JOptionPane.YES_OPTION:
                    result.deleteRow();
                    JOptionPane.showMessageDialog(null, "Data Berhasil dihapus.");
                    result.next();
                    result.first();
                    TampilData();
                    break;
                case JOptionPane.NO_OPTION:
                    TampilData();
                    break;
            }
        
        } catch (final SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFormAplikasiDatabase2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }  catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFormAplikasiDatabase2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFormAplikasiDatabase2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFormAplikasiDatabase2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFormAplikasiDatabase2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.ButtonGroup btnGroupJK;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKanan;
    private javax.swing.JButton btnKiri;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAlamat;
    private javax.swing.JLabel lblAngkatan;
    private javax.swing.JLabel lblFakultas;
    private javax.swing.JLabel lblJenisKelamin;
    private javax.swing.JLabel lblJurusan;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNim;
    private javax.swing.JLabel lblTanggalLahir;
    private javax.swing.JRadioButton rbL;
    private javax.swing.JRadioButton rbP;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtAngkatan;
    private javax.swing.JTextField txtFakultas;
    private javax.swing.JTextField txtJurusan;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNim;
    private javax.swing.JTextField txtTanggalLahir;
    // End of variables declaration//GEN-END:variables
}
